---
- hosts: jenkins-master
  become: true
  tasks:
    - name: Ajouter la clé Jenkins
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Ajouter le dépôt Jenkins
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Mettre à jour le cache APT
      apt:
        update_cache: yes

    - name: Installer Java 17
      apt:
        name: openjdk-17-jre
        state: present

    - name: Installer Jenkins
      apt:
        name: jenkins
        state: present

    - name: Activer Jenkins au démarrage
      service:
        name: jenkins
        enabled: yes

    - name: Démarrer Jenkins
      service:
        name: jenkins
        state: started